### ISSUE TITLE
Contacts.createOrUpdate data object issue

### ISSUE THREAD

**Issue by BrownieBits** [HGData/mk-node-hubspot#111]
This may be a typscript specific issue. When i try to use the contacts.createOrUpdate method i get an error. It requires two inputs into it. a string which would be the email and a data object. All the other methods like create require a JSON object but when i try to use it like this:
`const contact_data = {
        'properties': [
            {
            "property": "email",
            "value": postData.email
            },
            {
            "property": "firstname",
            "value": postData.f_name
            },
            {
            "property": "lastname",
            "value": postData.l_name
            },
            {
            "property": "company",
            "value": postData.company
            },
            {
            "property": "phone",
            "value": postData.phone
            },
            {
            "property": "state",
            "value": postData.state
            }
        ]
    };`

it gives me this error:
`[ts]
Argument of type '{ 'properties': { "property": string; "value": any; }[]; }' is not assignable to parameter of type '{}[]'.
  Property 'length' is missing in type '{ 'properties': { "property": string; "value": any; }[]; }'.`

i make the call like this:
`return hubspot.contacts.createOrUpdate(postData.email, contact_data)`

**Comment by BrownieBits** [comment]
@brainflake have you experienced this before?

**Comment by brainflake** [comment]
@PrimalIan I haven't used this with typescript, so no I haven't seen this. @pcothenet maybe you have?

**Comment by BrownieBits** [comment]
@pcothenet do you possibly have any help?

**Comment by pcothenet** [comment]
@PrimalIan I haven't actually used the library with Typescript. This could be an error with the types definition, let me check.

**Comment by pcothenet** [comment]
@PrimalIan I pushed a fix to the typescript definition file in version 1.3.3 (#112). Can you test and see if it fixes your issue?

**Comment by BrownieBits** [comment]
@pcothenet still getting an error. I am on version 1.3.3 and this is the error I'm getting:

TS2345: Argument of type '{ 'properties': { "property": string; "value": any; }[]; }' is not assignable to parameter of type 'any[]'.
  Property 'length' is missing in type '{ 'properties': { "property": string; "value": any; }[]; }'.

188     return hubspot.contacts.createOrUpdate(postData.email, contact_data).then(function(c_data){

**Comment by BrownieBits** [comment]
@pcothenet am I possibly creating the contact object wrong?

**Comment by BrownieBits** [comment]
Hey did we ever make any headway here?

**Comment by pcothenet** [comment]
@PrimalIan really sorry, I haven't been able to make progress here. 

Can you try making modifications to the type files directly in your `node_modules` and see if something works better. If so, you can create a PR for that change and I can publish it fast!

**Comment by pcothenet** [comment]
@PrimalIan is this one still an issue for you?

**Comment by BrownieBits** [comment]
I switched from running things in Typescript to using JS...Found too many packages that had typescript issues. So im not sure if this has been resolved.

**Comment by BrownieBits** [comment]
I could possibly spin up a test and see if i can get it to deploy if we need to

**Comment by pcothenet** [comment]
@PrimalIan thanks for the follow-up!

**Comment by yosyad** [comment]
Today I suffered from the same problem. I think that you guys should update contact data, the second argument of this function, from any[] to object.

**Comment by Hideman85** [comment]
I have the same issue, according to the doc (https://developers.hubspot.com/docs/methods/contacts/create_or_update) data should `createOrUpdate(email: string, data: {}): RequestPromise` like: `create(data: {}): RequestPromise` instead of `createOrUpdate(email: string, data: any[]): RequestPromise`.
Maybe it's also impact others API routes that you modify in [#112](https://github.com/MadKudu/node-hubspot/pull/112/commits/dba206f753a3996c3a0c264baa5297b1361005c2)

**Comment by Elyx0** [comment]
Typings are still wrong. Had to bypass by using `const Hubspot = require('hubspot');`
```
      const contactObj = {
        properties: [
          {
            property: 'email',
            value: attributes.customer.email,
          },
        ],
      };
      await hubspotClient.contacts.createOrUpdate(
        email,
        contactObj
      );
```

**Comment by pcothenet** [comment]
@Elyx0 which version are you using?

2.2 incorporates the fix described above: https://github.com/MadKudu/node-hubspot/blob/master/lib/typescript/contact.ts#L29
